'telecom.csv'

In [1]:
# preprocessing here

In [138]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestRegressor
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics 
from sklearn.metrics import accuracy_score

In [139]:
import pandas as pd
import numpy as np

In [147]:
data=pd.read_csv('telecom.csv')
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7853-GVUDZ,Female,0,Yes,Yes,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Credit card (automatic),20.15,20.15,Yes
1,6893-ODYYE,Male,0,No,No,50,Yes,No,Fiber optic,Yes,...,Yes,Yes,No,No,One year,Yes,Credit card (automatic),90.10,4549.45,No
2,0486-HECZI,Male,0,Yes,No,55,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,96.75,5238.9,Yes
3,8972-HJWNV,Female,1,Yes,No,7,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,84.55,646.85,Yes
4,9317-WZPGV,Female,1,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Bank transfer (automatic),79.75,159.4,Yes

In [148]:
data.nunique()

customerID          6000
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1519
TotalCharges        5622
Churn                  2
dtype: int64

In [149]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
data.isna().sum()

In [150]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        6000 non-null   object
 1   gender            6000 non-null   object
 2   SeniorCitizen     6000 non-null   int64
 3   Partner           6000 non-null   object
 4   Dependents        6000 non-null   object
 5   tenure            6000 non-null   int64
 6   PhoneService      6000 non-null   object
 7   MultipleLines     6000 non-null   object
 8   InternetService   6000 non-null   object
 9   OnlineSecurity    6000 non-null   object
 10  OnlineBackup      6000 non-null   object
 11  DeviceProtection  6000 non-null   object
 12  TechSupport       6000 non-null   object
 13  StreamingTV       6000 non-null   object
 14  StreamingMovies   6000 non-null   object
 15  Contract          6000 non-null   object
 16  PaperlessBilling  6000 non-null   object
 17  PaymentMethod     6000 non-null   object
 18  MonthlyCharges    6000 non-null   float64
 19  TotalCharges      6000 non-null   object
 20  Churn             6000 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 562.6+ KB

In [151]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [177]:
def preprocessing(dt):
    df = dt.copy() 
    df['gender']=le.fit_transform(df['gender'])
    df['Partner']=le.fit_transform(df['Partner'])
    df['Dependents']=le.fit_transform(df['Dependents'])
    df['PhoneService']=le.fit_transform(df['PhoneService'])
    df['PaperlessBilling']=le.fit_transform(df['PaperlessBilling'])
    df['Churn']=le.fit_transform(df['Churn'])
    #dt['TotalCharges'] = dt['TotalCharges'].astype('float16')
    df['TotalCharges']=pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0)
    df['MonthlyCharges'] = df['MonthlyCharges'].astype('float16')
    y = df['Churn']
    df.drop(['customerID','Churn'], axis = 1,inplace=True)
    dt=pd.get_dummies(df)
    return dt, y

In [178]:
df,y=preprocessing(data)

In [179]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,MultipleLines_No,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,1,1,1,1,20.15625,20.15,1,...,0,1,0,1,0,0,0,1,0,0
1,1,0,0,0,50,1,1,90.12500,4549.45,1,...,1,0,0,0,1,0,0,1,0,0
2,1,0,1,0,55,1,1,96.75000,5238.90,0,...,1,0,0,1,0,0,0,0,1,0
3,0,1,1,0,7,1,1,84.56250,646.85,0,...,0,0,1,1,0,0,0,0,1,0
4,0,1,0,0,2,1,1,79.75000,159.40,1,...,0,0,1,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,1,1,0,0,2,1,1,74.68750,165.40,1,...,1,0,0,1,0,0,0,0,1,0
5996,1,0,1,1,72,1,0,103.93750,7517.70,0,...,0,0,1,0,0,1,0,1,0,0
5997,0,1,0,0,7,1,1,64.93750,493.65,1,...,1,0,0,1,0,0,0,0,1,0
5998,1,0,1,0,70,1,0,25.15625,1940.85,0,...,0,1,0,0,0,1,1,0,0,0
5999,0,1,1,1,66,1,1,110.62500,7210.85,0,...,0,0,1,0,1,0,0,1,0,0

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 40 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   6000 non-null   int32
 1   SeniorCitizen                            6000 non-null   int64
 2   Partner                                  6000 non-null   int32
 3   Dependents                               6000 non-null   int32
 4   tenure                                   6000 non-null   int64
 5   PhoneService                             6000 non-null   int32
 6   PaperlessBilling                         6000 non-null   int32
 7   MonthlyCharges                           6000 non-null   float16
 8   TotalCharges                             6000 non-null   float64
 9   MultipleLines_No                         6000 non-null   uint8
 10  MultipleLines_No phone service           6000 non-null   uint8
 11  MultipleLines_Yes                        6000 non-null   uint8
 12  InternetService_DSL                      6000 non-null   uint8
 13  InternetService_Fiber optic              6000 non-null   uint8
 14  InternetService_No                       6000 non-null   uint8
 15  OnlineSecurity_No                        6000 non-null   uint8
 16  OnlineSecurity_No internet service       6000 non-null   uint8
 17  OnlineSecurity_Yes                       6000 non-null   uint8
 18  OnlineBackup_No                          6000 non-null   uint8
 19  OnlineBackup_No internet service         6000 non-null   uint8
 20  OnlineBackup_Yes                         6000 non-null   uint8
 21  DeviceProtection_No                      6000 non-null   uint8
 22  DeviceProtection_No internet service     6000 non-null   uint8
 23  DeviceProtection_Yes                     6000 non-null   uint8
 24  TechSupport_No                           6000 non-null   uint8
 25  TechSupport_No internet service          6000 non-null   uint8
 26  TechSupport_Yes                          6000 non-null   uint8
 27  StreamingTV_No                           6000 non-null   uint8
 28  StreamingTV_No internet service          6000 non-null   uint8
 29  StreamingTV_Yes                          6000 non-null   uint8
 30  StreamingMovies_No                       6000 non-null   uint8
 31  StreamingMovies_No internet service      6000 non-null   uint8
 32  StreamingMovies_Yes                      6000 non-null   uint8
 33  Contract_Month-to-month                  6000 non-null   uint8
 34  Contract_One year                        6000 non-null   uint8
 35  Contract_Two year                        6000 non-null   uint8
 36  PaymentMethod_Bank transfer (automatic)  6000 non-null   uint8
 37  PaymentMethod_Credit card (automatic)    6000 non-null   uint8
 38  PaymentMethod_Electronic check           6000 non-null   uint8
 39  PaymentMethod_Mailed check               6000 non-null   uint8
dtypes: float16(1), float64(1), int32(5), int64(2), uint8(31)
memory usage: 451.2 KB

Split data into 2 parts, take the small one as the final test. You will be using for each model's final evaluation

In [181]:
 xTrain,xTest,yTrain,yTest=train_test_split(df,y,random_state=1,test_size=0.16)

In [182]:
traindf=xTrain
trainy=yTrain

In [183]:
 x_Train,x_Test,y_Train,y_Test=train_test_split(traindf,trainy,random_state=1,test_size=0.16)

In [184]:
norm=MinMaxScaler().fit(x_Train)
normx_Train=pd.DataFrame(data=norm.transform(x_Train),columns=x_Train.columns)
normx_Test=pd.DataFrame(data=norm.transform(x_Test),columns=x_Test.columns)

In [185]:
normx_Test

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,MultipleLines_No,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1.0,0.0,0.0,0.0,0.708333,1.0,0.0,0.625156,0.470448,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.319444,1.0,1.0,0.854919,0.284416,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.208333,1.0,1.0,0.777709,0.164281,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.208333,1.0,1.0,0.372976,0.103606,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.958333,1.0,1.0,0.668742,0.679048,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802,0.0,0.0,0.0,0.0,0.194444,1.0,0.0,0.330635,0.083807,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
803,0.0,0.0,1.0,0.0,0.944444,1.0,0.0,0.075187,0.220097,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
804,0.0,0.0,0.0,0.0,0.694444,0.0,0.0,0.213574,0.222544,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
805,0.0,0.0,1.0,0.0,0.763889,1.0,0.0,0.384184,0.358333,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
806,0.0,0.0,0.0,0.0,0.013889,1.0,0.0,0.720423,0.010426,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

# Build 5 classification models

logistic regression, decision tree, random forest, knn, svm

#### tips
<br>
1. use cross validation
<br>
2. use same splits for all classifiers (to have correct comparison)
<br>
3. build a table to show statistics for all classifiers (at least - accuracy, precision and recall. Any more component would be a +)

In [186]:
def KFiold(data,model,lebel,folds=10):
    kf = KFold(n_splits=folds)
    score_test = []
    score_train=[]
    for train_index, test_index in kf.split(data):
        X_train, X_test = data.loc[train_index], data.loc[test_index]
        y_train, y_test = y[train_index], y[test_index]
    
        m=model.fit(X_train, y_train)
        predictions_test = model.predict(X_test)
        predictions_train = model.predict(X_train)
        score_test.append(score(x_test,predictions_test))
        score_train.append(score(x_train,predictions_train))
        print('test score mean',np.mean(score_test),'train score mean' ,np.mean(score_test))

In [187]:
##Logistic regr

In [188]:
lg=LogisticRegression(random_state=0)
lg.fit(x_Train,y_Train)
pred_y=lg.predict(x_Test)
print("Accuracy:",metrics.accuracy_score(y_Test, lg.predict(x_Test)))
print("Precision:",metrics.precision_score(y_Test, lg.predict(x_Test)))
print("Recall:",metrics.recall_score(y_Test, lg.predict(x_Test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Accuracy: 0.7831474597273854
Precision: 0.616580310880829
Recall: 0.5409090909090909

In [ ]:
## Kfold for logistic reg

In [ ]:
kf = KFold(n_splits=5)
    score_test = []
    precision=[]
    recall=[]
    for train_index, test_index in kf.split(x_Train):
        x_train, x_test = x_Train.loc[train_index], x_Train.loc[test_index]
        y_train, y_test = y_Train[train_index], y_Train[test_index]
    
        lg=LogisticRegression(random_state=0)
        lg.fit(x_train, y_train)
        predictions_test = model.predict(x_test)
        predictions_train = model.predict(x_train)
        score_test.append(metrics.accuracy_score(y_Test, m.predict(x_Test))
        precision.append(metrics.precision_score(y_Test, m.predict(x_Test))
        recall.append(metrics.recall_score(y_Test, m.predict(x_Test))
        print('accuracy score',np.mean(score_test),'precision ' ,np.mean(precision),'recall',np.mean(recall))

In [ ]:
##des tree

In [ ]:
dt = DecisionTreeClassifier(max_depths=5)
dt.fit(x_Train,y_Train)
print('Test score for des tree',dt.score(x_Test, y_Test))
print('Train score for des tree',dt.score(x_Train, y_Train))

In [89]:
## using KFold for des tree

In [ ]:
def run_cross_validation_on_trees(X, y, tree_depths, cv=5, scoring='accuracy'):
    cv_scores_list = []
    cv_scores_std = []
    cv_scores_mean = []
    accuracy_scores = []
    for depth in tree_depths:
        tree_model = DecisionTreeClassifier(max_depth=depth)
        cv_scores = cross_val_score(tree_model, X, y, cv=cv, scoring=scoring)
        cv_scores_list.append(cv_scores)
        cv_scores_mean.append(cv_scores.mean())
        cv_scores_std.append(cv_scores.std())
        accuracy_scores.append(tree_model.fit(X, y).score(X, y))
    cv_scores_mean = np.array(cv_scores_mean)
    cv_scores_std = np.array(cv_scores_std)
    accuracy_scores = np.array(accuracy_scores)
    return cv_scores_mean, cv_scores_std, accuracy_scores

In [ ]:
run_cross_validation_on_trees(x_Train,y_Train,3)

In [ ]:
##rendom forest

In [70]:
rf=RandomForestRegressor(n_estimators=10, random_state=0)
rf.fit(x_Train,y_Train)
print('Test score for rand forest',rf.score(x_Test, y_Test))
print('Train score for rand forest',rf.score(x_Train, y_Train))

Test score for rand forest 0.1865991164627534
Train score for rand forest 0.859926988605272

In [253]:
## KNN

In [71]:
knn= KNeighborsClassifier(n_neighbors=5)
knn.fit(traindf,trainy)
pred_y= knn.predict(x_Test)
print("Accuracy:",metrics.accuracy_score(y_Test, knn.predict(x_Test)))
print("Precision:",metrics.precision_score(y_Test, knn.predict(x_Test)))
print("Recall:",metrics.recall_score(y_Test, pred_y))

Accuracy: 0.828996282527881
Precision: 0.7135416666666666
Recall: 0.6227272727272727

In [ ]:
print("Accuracy:",metrics.accuracy_score(yTest, knn.predict(xTest)))
print("Precision:",metrics.precision_score(y_Test, knn.predict(xTest)))
print("Recall:",metrics.recall_score(yTest, knn.predict(xTest)))

In [ ]:
## SVM

In [ ]:
svm = svm.SVC(kernel='linear')
svm.fit(traindf,trainy)
pred_y=svm.predict(x_Test)
print("Accuracy:",metrics.accuracy_score(y_Test, pred_y))
print("Precision:",metrics.precision_score(y_Test, pred_y))
print("Recall:",metrics.recall_score(y_Test, pred_y))

#### choose the best model. Either retrain it or copy it in the cell below

In [ ]:
# final_model = ...().fit(...) # example for retraining

In [ ]:
knn= KNeighborsClassifier(n_neighbors=5).fit(traindf,trainy)

In [ ]:
dt=DecisionTreeClassifier(max_depths=5).fit(x_Train,y_Train)